"""
Django settings for tttproject project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
from django.utils.crypto import get_random_string
SECRET_KEY = os.environ.get('SECRET_KEY', get_random_string(128))

# SECURITY WARNING: don't run with debug turned on in production!
if 'PORT' in os.environ:
    DEBUG = False
else:
    DEBUG = True

if 'PORT' in os.environ:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = []


INSTALLED_APPS = [
    'tttapp',
]

MIDDLEWARE = [
]

ROOT_URLCONF = 'tttproject.urls'

TEMPLATES = []

WSGI_APPLICATION = 'tttproject.wsgi.application'

# No databases. See README.md.
DATABASES = {}

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
